apiVersion: v1
name: cert-manager-vultr
version: 0.1.0
description: Vultr integration for cert-manager
keywords:
  - cert-manager
  - vultr
home: https://github.com/swrm-io/cert-manager-vultr

maintainers:
  - name: Richard Cox
    url: https://github.com/swrm-io/

appVersion: "v0.1.0"
